# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descriptio',
            new_name='description',
        ),
    ]
